#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define FPS 60

#define PLAYER_SPEED 200.0f
#define PLAYER_ROTATION_SPEED 3.0f
#define PLAYER_RADIUS 15.0f
#define PLAYER_MAX_SPEED 400.0f
#define FRICTION 0.98f

#define BULLET_SPEED 400.0f
#define BULLET_LIFETIME 1.5f
#define BULLET_RADIUS 2.0f

#define ASTEROID_SPEED_MIN 50.0f
#define ASTEROID_SPEED_MAX 150.0f
#define ASTEROID_ROTATION_SPEED_MIN 1.0f
#define ASTEROID_ROTATION_SPEED_MAX 3.0f
#define ASTEROID_RADIUS_LARGE 40.0f
#define ASTEROID_RADIUS_MEDIUM 25.0f
#define ASTEROID_RADIUS_SMALL 15.0f
#define ASTEROID_SPAWN_DISTANCE 100.0f  // Minimum distance from player spawn

// Difficulty-based constants
#define BULLET_LIMIT_EASY 15
#define BULLET_LIMIT_NORMAL 10
#define BULLET_LIMIT_HARD 5

#define ASTEROID_SPEED_MIN_EASY 30.0f
#define ASTEROID_SPEED_MAX_EASY 80.0f
#define ASTEROID_SPEED_MIN_NORMAL 50.0f
#define ASTEROID_SPEED_MAX_NORMAL 150.0f
#define ASTEROID_SPEED_MIN_HARD 100.0f
#define ASTEROID_SPEED_MAX_HARD 200.0f

#endif